export const PRODUCTO_LISTA_REQUEST = "PRODUCTO_LISTA_REQUEST";
export const PRODUCTO_LISTA_EXITO = "PRODUCTO_LISTA_EXITO";
export const PRODUCTO_LISTA_ERROR = "PRODUCTO_LISTA_ERROR";

export const PRODUCTO_DETALLE_REQUEST = "PRODUCTO_DETALLE_REQUEST";
export const PRODUCTO_DETALLE_EXITO = "PRODUCTO_DETALLE_EXITO";
export const PRODUCTO_DETALLE_ERROR = "PRODUCTO_DETALLE_ERROR";
