// Logear Usuario
export const USUARIO_LOGIN_REQUEST = "USUARIO_LOGIN_REQUEST";
export const USUARIO_LOGIN_EXITO = "USUARIO_LOGIN_EXITO";
export const USUARIO_LOGIN_ERROR = "USUARIO_LOGIN_ERROR";
export const USUARIO_LOGOUT = "USUARIO_LOGOUT";

// Registrar Usuario
export const USUARIO_REGISTRAR_REQUEST = "USUARIO_REGISTRAR_REQUEST";
export const USUARIO_REGISTRAR_EXITO = "USUARIO_REGISTRAR_EXITO";
export const USUARIO_REGISTRAR_ERROR = "USUARIO_REGISTRAR_ERROR";

// Detalles Usuario
export const USUARIO_DETALLES_REQUEST = "USUARIO_DETALLES_REQUEST";
export const USUARIO_DETALLES_EXITO = "USUARIO_DETALLES_EXITO";
export const USUARIO_DETALLES_ERROR = "USUARIO_DETALLES_ERROR";

// ACUTALIZAR Usuario
export const USUARIO_ACTUALIZAR_PERFIL_REQUEST =
  "USUARIO_ACTUALIZAR_PERFIL_REQUEST";
export const USUARIO_ACTUALIZAR_PERFIL_EXITO =
  "USUARIO_ACTUALIZAR_PERFIL_EXITO";
export const USUARIO_ACTUALIZAR_PERFIL_ERROR =
  "USUARIO_ACTUALIZAR_PERFIL_ERROR";
export const USUARIO_ACTUALIZAR_PERFIL_RESET =
  "USUARIO_ACTUALIZAR_PERFIL_RESET";
