// Logear Usuario
export const USUARIO_LOGIN_REQUEST = "USUARIO_LOGIN_REQUEST";
export const USUARIO_LOGIN_EXITO = "USUARIO_LOGIN_EXITO";
export const USUARIO_LOGIN_ERROR = "USUARIO_LOGIN_ERROR";
export const USUARIO_LOGOUT = "USUARIO_LOGOUT";

// Registrar Usuario
export const USUARIO_REGISTRAR_REQUEST = "USUARIO_REGISTRAR_REQUEST";
export const USUARIO_REGISTRAR_EXITO = "USUARIO_REGISTRAR_EXITO";
export const USUARIO_REGISTRAR_ERROR = "USUARIO_REGISTRAR_ERROR";
