export const USUARIO_LOGIN_REQUEST = "USUARIO_LOGIN_REQUEST";
export const USUARIO_LOGIN_EXITO = "USUARIO_LOGIN_EXITO";
export const USUARIO_LOGIN_ERROR = "USUARIO_LOGIN_ERROR";
export const USUARIO_LOGOUT = "USUARIO_LOGOUT";
